INSERT INTO life_vehicle_colors(color, slug) VALUES('Brown', 'Brown');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Digi_Desert', 'Digi Desert');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Black', 'Black');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Blue', 'Blue');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Red', 'Red');
INSERT INTO life_vehicle_colors(color, slug) VALUES('White', 'White');
INSERT INTO life_vehicle_colors(color, slug) VALUES('DigiGreen', 'Digi Green');
INSERT INTO life_vehicle_colors(color, slug) VALUES('HunterCamo', 'Hunter Camo');
INSERT INTO life_vehicle_colors(color, slug) VALUES('RebelCamo', 'Rebel Camo');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Yellow', 'Yellow');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Dark_Red', 'Dark Red');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Blue_White', 'Blue / White');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Taxi', 'Taxi');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Polizei', 'Polizei');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Silver', 'Silver');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Orange', 'Orange');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Feuerwehr', 'Feuerwehr');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Dark_Blue', 'Dark Blue');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Black_White', 'Black / White');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Beige', 'Beige');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Green', 'Green');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Civ_Blue', 'Civ Blue');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Civ_Red', 'Civ Red');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Blueline', 'Blueline');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Elliptical', 'Elliptical');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Furious', 'Furious');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Jeans_Blue', 'Jeans Blue');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Speedy_Redline', 'Speedy Redline');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Sunset', 'Sunset');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Vrana', 'Vrana');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Waves_Blue', 'Waves Blue');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Rebel_Digital', 'Rebel Digital');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Digi_Green', 'Digi Green');
INSERT INTO life_vehicle_colors(color, slug) VALUES('BlackCop', 'Black');
INSERT INTO life_vehicle_colors(color, slug) VALUES('White_Blue', 'White / Blue');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Desert_Digi', 'Desert Digi');
INSERT INTO life_vehicle_colors(color, slug) VALUES('EMS_White', 'EMS White');
INSERT INTO life_vehicle_colors(color, slug) VALUES('EMS', 'Feuerwehr');
INSERT INTO life_vehicle_colors(color, slug) VALUES('Rebell', 'Rebell');