INSERT INTO life_virtual_items(name, slug) VALUES('pickaxe', 'Spitzhacke');
INSERT INTO life_virtual_items(name, slug) VALUES('defibrilator', 'Defibrilator');
INSERT INTO life_virtual_items(name, slug) VALUES('fuelEmpty', 'Benzinkanister (Leer)');
INSERT INTO life_virtual_items(name, slug) VALUES('fuelFull', 'Benzinkanister (Voll)');
INSERT INTO life_virtual_items(name, slug) VALUES('lockpick', 'Dietrich');
INSERT INTO life_virtual_items(name, slug) VALUES('blastingcharge', 'Sprengladung');
INSERT INTO life_virtual_items(name, slug) VALUES('boltcutter', 'Bolzenschneider');
INSERT INTO life_virtual_items(name, slug) VALUES('defusekit', 'Entschärfungs Kit');
INSERT INTO life_virtual_items(name, slug) VALUES('coffee', 'Kaffee');
INSERT INTO life_virtual_items(name, slug) VALUES('waterBottle', 'Wasserflasche');
INSERT INTO life_virtual_items(name, slug) VALUES('wodka', 'Wodka');
INSERT INTO life_virtual_items(name, slug) VALUES('bier', 'Bier');
INSERT INTO life_virtual_items(name, slug) VALUES('redgull', 'Wild Energy');
INSERT INTO life_virtual_items(name, slug) VALUES('steak', 'Steak');
INSERT INTO life_virtual_items(name, slug) VALUES('bacon', 'Taktischer Speck');
INSERT INTO life_virtual_items(name, slug) VALUES('firstaidkit', 'Verbandskasten');
INSERT INTO life_virtual_items(name, slug) VALUES('donuts', 'Donut');
INSERT INTO life_virtual_items(name, slug) VALUES('kabelbinder', 'Kabelbinder');
INSERT INTO life_virtual_items(name, slug) VALUES('schloss', 'Schloss');
INSERT INTO life_virtual_items(name, slug) VALUES('medmarihuana', 'Medizinisches Marihuana');
INSERT INTO life_virtual_items(name, slug) VALUES('danger', 'Gefahrengut');
INSERT INTO life_virtual_items(name, slug) VALUES('dangernuclear', 'Radioaktive Substanz');
INSERT INTO life_virtual_items(name, slug) VALUES('moonshineP', 'Moonshine');
INSERT INTO life_virtual_items(name, slug) VALUES('apple', 'Apfel');
INSERT INTO life_virtual_items(name, slug) VALUES('bananen', 'Banane');
INSERT INTO life_virtual_items(name, slug) VALUES('pfirsich', 'Pfirsich');
INSERT INTO life_virtual_items(name, slug) VALUES('traubenU', 'Trauben');
INSERT INTO life_virtual_items(name, slug) VALUES('diamantenU', 'Ungeschliffene Diamanten');
INSERT INTO life_virtual_items(name, slug) VALUES('eisenU', 'Eisenerz');
INSERT INTO life_virtual_items(name, slug) VALUES('erdgasU', 'Petrolium');
INSERT INTO life_virtual_items(name, slug) VALUES('kupferU', 'Kupfererz');
INSERT INTO life_virtual_items(name, slug) VALUES('sandU', 'Sand');
INSERT INTO life_virtual_items(name, slug) VALUES('salzU', 'Salz');
INSERT INTO life_virtual_items(name, slug) VALUES('ziegelU', 'Lehm');
INSERT INTO life_virtual_items(name, slug) VALUES('paketeP', 'Pakete');
INSERT INTO life_virtual_items(name, slug) VALUES('heliumP', 'Helium');
INSERT INTO life_virtual_items(name, slug) VALUES('kokainU', 'Unverarbeitetes Kokain');
INSERT INTO life_virtual_items(name, slug) VALUES('heroinU', 'Unverarbeitetes Heroin');
INSERT INTO life_virtual_items(name, slug) VALUES('marihuanaU', 'Cannabis');
INSERT INTO life_virtual_items(name, slug) VALUES('dunkleP', 'Dunkle Materie');
INSERT INTO life_virtual_items(name, slug) VALUES('kleidungU', 'Baumwolle');
INSERT INTO life_virtual_items(name, slug) VALUES('oilU', 'Öl');
INSERT INTO life_virtual_items(name, slug) VALUES('relikt', 'Unidentifiziertes Relikt');
INSERT INTO life_virtual_items(name, slug) VALUES('diamantenP', 'Geschliffene Diamanten');
INSERT INTO life_virtual_items(name, slug) VALUES('marihuanaP', 'Marihuana');
INSERT INTO life_virtual_items(name, slug) VALUES('heroinP', 'Verarbeitetes Heroin');
INSERT INTO life_virtual_items(name, slug) VALUES('kokainP', 'Verarbeitetes Kokain');
INSERT INTO life_virtual_items(name, slug) VALUES('kleidungP', 'Kleidung');
INSERT INTO life_virtual_items(name, slug) VALUES('ziegelP', 'Ziegel');
INSERT INTO life_virtual_items(name, slug) VALUES('stahlP', 'Stahlbeton');
INSERT INTO life_virtual_items(name, slug) VALUES('eisenP', 'Eisenbarren');
INSERT INTO life_virtual_items(name, slug) VALUES('salzP', 'Raffiniertes Salz');
INSERT INTO life_virtual_items(name, slug) VALUES('sandP', 'Glas');
INSERT INTO life_virtual_items(name, slug) VALUES('kupferP', 'Kupferbarren');
INSERT INTO life_virtual_items(name, slug) VALUES('erdgasP', 'Erdgas');
INSERT INTO life_virtual_items(name, slug) VALUES('traubenP', 'Wein');
INSERT INTO life_virtual_items(name, slug) VALUES('oilP', 'Raffiniertes Öl');
INSERT INTO life_virtual_items(name, slug) VALUES('Relikt_0', 'Wertloses Artefakt');
INSERT INTO life_virtual_items(name, slug) VALUES('Relikt_1', 'Minderes Artefakt');
INSERT INTO life_virtual_items(name, slug) VALUES('Relikt_2', 'Unindentifiziertes Artefakt');
INSERT INTO life_virtual_items(name, slug) VALUES('Relikt_3', 'Ungewöhnliches Artefakt');
INSERT INTO life_virtual_items(name, slug) VALUES('Relikt_4', 'Wertvolles Artefakt');
INSERT INTO life_virtual_items(name, slug) VALUES('Salema_F', 'Salema');
INSERT INTO life_virtual_items(name, slug) VALUES('Ornate_random_F', 'Ornate');
INSERT INTO life_virtual_items(name, slug) VALUES('Mackerel_F', 'Mackerel');
INSERT INTO life_virtual_items(name, slug) VALUES('Tuna_F', 'Tuna');
INSERT INTO life_virtual_items(name, slug) VALUES('Mullet_F', 'Mullet');
INSERT INTO life_virtual_items(name, slug) VALUES('CatShark_F', 'Cat Shark');
INSERT INTO life_virtual_items(name, slug) VALUES('Turtle_F', 'Turtle');
INSERT INTO life_virtual_items(name, slug) VALUES('adrenalin', 'Adrenalinspritze');
INSERT INTO life_virtual_items(name, slug) VALUES('briefeP', 'Briefe');