INSERT INTO life_licenses(license, slug) VALUES('driver', 'Führerschein');
INSERT INTO life_licenses(license, slug) VALUES('boat', 'Bootsschein');
INSERT INTO life_licenses(license, slug) VALUES('air', 'Pilotenlizenz');
INSERT INTO life_licenses(license, slug) VALUES('gun', 'Waffenschein');
INSERT INTO life_licenses(license, slug) VALUES('dive', 'Taucherschein');
INSERT INTO life_licenses(license, slug) VALUES('diamanten', 'Diamantenverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('kokain', 'Kokain Verarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('heroin', 'Heroinausbildung');
INSERT INTO life_licenses(license, slug) VALUES('marihuana', 'Marihuanaverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('sand', 'Glasbläserei');
INSERT INTO life_licenses(license, slug) VALUES('salz', 'Salz Verarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('kupfer', 'Kupferverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('eisen', 'Eisenverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('erdgas', 'Erdgasverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('ziegel', 'Lehmverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('kleidung', 'Baumwollverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('wein', 'Weinverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('rebel', 'Rebellenausbildung');
INSERT INTO life_licenses(license, slug) VALUES('lkw', 'LKW-Führerschein');
INSERT INTO life_licenses(license, slug) VALUES('defi', 'Feldausbildung');
INSERT INTO life_licenses(license, slug) VALUES('moonshine', 'Moonshineverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('haus', 'Hauseigentümer');
INSERT INTO life_licenses(license, slug) VALUES('relikt', 'Reliktverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('baustoff', 'Baustoffverarbeitung');
INSERT INTO life_licenses(license, slug) VALUES('adrenalin', 'Medizinausbildung');
INSERT INTO life_licenses(license, slug) VALUES('zivil', 'Zivilpolizei');