INSERT INTO life_vehicle_materials(material, slug) VALUES('whiteBlueGlow', 'Skyline [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('lightBlueGlow', 'Himmelsblau [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('darkBlueGlow', 'Nachtblau [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('redGlow', 'Blutrot [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('lightGreenGlow', 'Blattgrün [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('darkGreenGlow', 'Monstergrün [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('pinkLadyGlow', 'Pink Lady [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('lilaGlow', 'Violette Tulpe [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('orangeGlow', 'Orange [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('manderinGlow', 'Mandarin [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('lemonGlow', 'Limone [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('yellowGlow', 'Sonnengelb [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('silentBlueGlow', 'Stilles blau [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('silentgreenGlow', 'Stilles grün [Leuchtet]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('firestormRedEditionShine', 'Firestorm Red Edition [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('firestormYellowEditionShine', 'Firestorm Yellow Edition [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('csgoFadeShine', 'CS:GO Fade [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('flipFlopGreenShine', 'Flip Flop Green [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('flipFlopYellowShine', 'Flip Flop Yellow [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('girlsClubShine', 'Girls Club [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('goldenRetrieverShine', 'Golden Retriever [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('lavaShine', 'Lava [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('oceanShine', 'Ocean [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('crazyLasyShine', 'Crazy Lasy [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('twinColoursShine', 'Twin Colours [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('stealthShine', 'Stealth [Reflexion]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('blueUltimate', 'ULTIMATE BLUE [Beides]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('redUltimate', 'ULTIMATE RED [Beides]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('greenUltimate', 'ULTIMATE GREEN [Beides]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('fadeUltimate', 'ULTIMATE FADE [Beides]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('reverse1Ultimate', 'ULTIMATE REVERSE 1 [Beides]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('reverse2Ultimate', 'ULTIMATE REVERSE 2 [Beides]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('reverse3Ultimate', 'ULTIMATE REVERSE 3 [Beides]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('chrom', 'Much Chrome such WOW! [Chrome]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('redChrome', 'Rubin Rot [Chrome]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('greenChrome', 'Smaragd Grün [Chrome]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('blueChrome', 'Saphir Blau [Chrome]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('tuerkisChrome', 'Apatit Türkis [Chrome]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('pinkChrome', 'Amethyst Pink [Chrome]');
INSERT INTO life_vehicle_materials(material, slug) VALUES('gold', '$$$ GOLD $$$');