INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Quadbike_01_F', '1', 'Quad Bike');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Offroad_01_F', '1', 'Offroad');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_SUV_01_F', '1', 'SUV');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Hatchback_01_sport_F', '1', 'Hatchback (Sport)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Hatchback_01_F', '1', 'Hatchback');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_F', '1', 'Kart');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_Fuel_F', '1', 'Kart (Fuel)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_Red_F', '1', 'Kart (Redstone)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_Vrana_F', '1', 'Kart (Vrana)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_green_F', '1', 'Kart (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_orange_F', '1', 'Kart (Orange)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_white_F', '1', 'Kart (White)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_yellow_F', '1', 'Kart (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_black_F', '1', 'Kart (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Kart_01_Blu_F', '1', 'Kart (Bluking)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Van_01_box_F', '1', 'Truck Boxer');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Van_01_transport_F', '1', 'Truck');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Truck_01_transport_F', '1', 'HEMTT Transport');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Truck_01_covered_F', '1', 'HEMTT Transport (Covered)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_T_LSV_02_unarmed_F', '1', 'Qilin (Unarmed)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Van_01_fuel_F', '1', 'Fuel Truck');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Truck_03_transport_F', '1', 'Tempest Transport');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Truck_02_fuel_F', '1', 'Zamak Fuel');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Truck_01_box_F', '1', 'HEMTT Box');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Truck_03_covered_F', '1', 'Tempest Transport (Covered)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Truck_03_device_F', '1', 'Tempest (Device)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Heli_Light_01_F', '2', 'MH-9 Hummingbird');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Heli_Light_02_unarmed_F', '2', 'PO-30 Orca (Unarmed)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Plane_Civil_01_F', '2', 'Caesar BTT');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Plane_Civil_01_racing_F', '2', 'Caesar BTT (Racing)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_Heli_light_03_unarmed_F', '2', 'WY-55 Hellcat (Unarmed)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Heli_Transport_01_F', '2', 'UH-80 Ghost Hawk');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Heli_Transport_03_unarmed_F', '2', 'CH-67 Huron (Unarmed)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_Plane_Fighter_03_AA_F', '2', 'A-143 Buzzard (AA)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_T_VTOL_01_infantry_F', '2', 'V-44 X Blackfish (Infantry Transport)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_T_VTOL_01_vehicle_F', '2', 'V-44 X Blackfish (Vehicle Transport)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Heli_Transport_04_F', '2', 'Mi-290 Taru');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Heli_Transport_04_box_F', '2', 'Mi-290 Taru (Cargo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_Heli_Transport_02_F', '2', 'CH-49 Mohawk');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Boat_Armed_01_minigun_F', '3', 'Speedboat Minigun');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Boat_Transport_01_F', '3', 'Assault Boat');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_SDV_01_F', '1', 'SDV');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Rubberboat', '3', 'Rescue Boat');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Boat_Civil_01_F', '3', 'Motorboat');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Boat_Civil_01_rescue_F', '3', 'Motorboat (Rescue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Boat_Transport_02_F', '3', 'RHIB');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Scooter_Transport_01_F', '3', 'Water Scooter');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_G_Offroad_01_armed_F', '1', 'Offroad (HMG)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_C_Offroad_02_unarmed_F', '1', 'MB 4WD');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_MRAP_03_F', '1', 'Strider');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_MRAP_01_F', '1', 'Hunter');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Boat_Civil_01_police_F', '3', 'Motorboat (Police)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Heli_Attack_01_F', '2', 'AH-99 Blackfoot');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Van_02_transport_F', '1', 'Van Transport');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_G_Boat_Transport_02_F', '3', 'RHIB');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Van_02_vehicle_F', '1', 'Van (Cargo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Van_02_medevac_F', '1', 'Van (Ambulance)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Heli_Attack_02_F', '2', 'Mi-48 Kajman');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Heli_Transport_04_bench_F', '2', 'Mi-290 Taru (Bench)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Heli_Transport_04_covered_F', '2', 'Mi-290 Taru (Transport)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Plane_Fighter_01_F', '2', 'F/A-181 Black Wasp II');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_Plane_Fighter_03_CAS_F', '2', 'A-143 Buzzard (CAS)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Plane_Fighter_02_F', '2', 'To-201 Shikra');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Plane_CAS_01_F', '2', 'A-164 Wipeout (CAS)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Plane_CAS_02_F', '2', 'To-199 Neophron (CAS)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_Plane_Fighter_04_F', '2', 'A-149 Gryphon');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_T_LSV_01_unarmed_F', '1', 'Prowler (Unarmed)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_MRAP_01_hmg_F', '1', 'Hunter HMG');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Heli_Attack_02_black_F', '2', 'Mi-48 Kajman (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_E_Offroad_01_covered_F', '1', 'Offroad (Covered)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Quadbike_01_F', '1', 'Quad Bike');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Truck_03_repair_F', '1', 'Tempest Repair');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Truck_02_covered_F', '1', 'Zamak Transport (Covered)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Truck_02_transport_F', '1', 'Zamak Transport');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Offroad_02_unarmed_F', '1', 'MB 4WD');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Truck_03_fuel_F', '1', 'Tempest Fuel');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Truck_01_fuel_F', '1', 'HEMTT Fuel');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_T_Truck_03_fuel_ghex_F', '1', 'Tempest Fuel');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_Truck_02_fuel_F', '1', 'Zamak Fuel');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_G_Van_01_fuel_F', '1', 'Fuel Truck');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_T_Truck_01_box_F', '1', 'HEMTT Box');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Truck_01_mover_F', '1', 'HEMTT');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_T_Truck_01_transport_F', '1', 'HEMTT Transport');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_Truck_02_transport_F', '1', 'Zamak Transport');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Lifeboat', '3', 'Rescue Boat');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('I_Truck_02_covered_F', '1', 'Zamak Transport (Covered)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_Heli_Transport_04_medevac_F', '2', 'Mi-290 Taru (Medical)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('C_Heli_Light_01_civil_F', '2', 'M-900');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_T_VTOL_02_infantry_F', '2', 'Y-32 Xian (Infantry Transport)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Heli_Transport_03_F', '2', 'CH-67 Huron');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_APC_Wheeled_02_rcws_F', '1', 'MSE-3 Marid');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('O_MRAP_02_F', '1', 'Ifrit');