INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_CombatUniform', '4', 'Combat Fatigues [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_CombatUniform_shortsleeve', '4', 'Combat Fatigues [AAF] (Rolled-up)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Scientist', '4', 'Scientist Clothes');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_blk', '4', 'Cap (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_grn', '4', 'Cap (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_oli', '4', 'Cap (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_tan', '4', 'Cap (Tan)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_blk_Raven', '4', 'Cap [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_brn_SPECOPS', '4', 'Cap [OPFOR]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_blu', '4', 'Cap (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_red', '4', 'Cap (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_blk_CMMG', '4', 'Cap (CMMG)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_blk_ION', '4', 'Cap (ION)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_grn_BI', '4', 'Cap (BI)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_press', '4', 'Cap (Press)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_Orange_IDAP_F', '4', 'Cap (Orange) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_Black_IDAP_F', '4', 'Cap (Black) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_White_IDAP_F', '4', 'Cap (White) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_khaki_specops_UK', '4', 'Cap (UK)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_tan_specops_US', '4', 'Cap (US MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_BandMask_blk', '4', 'Bandana Mask (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_oli_hs', '4', 'Cap (Olive, Headset)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_headphones', '4', 'Rangemaster Cap');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Cap_marshal', '4', 'Marshal Cap');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Hat_tan', '4', 'Hat (Tan)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Hat_grey', '4', 'Hat (Grey)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Hat_brown', '4', 'Hat (Brown)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Hat_checker', '4', 'Hat (Checker)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Hat_Safari_olive_F', '4', 'Safari Hat (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Hat_Safari_sand_F', '4', 'Safari Hat (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Hat_blue', '4', 'Hat (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Hat_camo', '4', 'Hat (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_StrawHat', '4', 'Straw Hat');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_StrawHat_dark', '4', 'Straw Hat (Dark)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_TurbanO_blk', '4', 'Black Turban');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Bandanna_camo', '4', 'Bandana (Woodland)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Bandanna_cbr', '4', 'Bandana (Coyote)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Bandanna_gry', '4', 'Bandana (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Bandanna_khk', '4', 'Bandana (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Bandanna_mcamo', '4', 'Bandana (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Bandanna_sgg', '4', 'Bandana (Sage)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Bandanna_surfer', '4', 'Bandana (Surfer)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Bandanna_khk_hs', '4', 'Bandana (Headset)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Watchcap_blk', '4', 'Beanie');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Watchcap_camo', '4', 'Beanie (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Watchcap_khk', '4', 'Beanie (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Watchcap_sgg', '4', 'Beanie (Sage)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Booniehat_mcamo', '4', 'Booniehat (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Booniehat_khk_hs', '4', 'Booniehat (Headset)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Booniehat_tna_F', '4', 'Booniehat (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Construction_basic_yellow_F', '4', 'Hard Hat (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Construction_basic_orange_F', '4', 'Hard Hat (Orange)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Construction_basic_red_F', '4', 'Hard Hat (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Construction_headset_black_F', '4', 'Hard Hat (Black, Headset)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Construction_basic_vrana_F', '4', 'Hard Hat (Vrana)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Construction_basic_white_F', '4', 'Hard Hat (White)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_blue', '4', 'Military Cap (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_dgtl', '4', 'Military Cap [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_gry', '4', 'Military Cap (Grey)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_mcamo', '4', 'Military Cap (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_ocamo', '4', 'Military Cap (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_oucamo', '4', 'Military Cap (Urban)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_rucamo', '4', 'Military Cap (Russia)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_ghex_F', '4', 'Military Cap (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_MilCap_tna_F', '4', 'Military Cap (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Helmet_Skate', '4', 'Skate Helmet');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_EarProtectors_yellow_F', '4', 'Ear Protectors (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_EarProtectors_orange_F', '4', 'Ear Protectors (Orange)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_EarProtectors_red_F', '4', 'Ear Protectors (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_EarProtectors_black_F', '4', 'Ear Protectors (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_EarProtectors_white_F', '4', 'Ear Protectors (White)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HeadSet_yellow_F', '4', 'Headset (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HeadSet_orange_F', '4', 'Headset (Orange)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HeadSet_red_F', '4', 'Headset (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HeadSet_black_F', '4', 'Headset (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HeadSet_white_F', '4', 'Headset (White)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_BandMask_reaper', '4', 'Bandana Mask (Reaper)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_PASGT_basic_blue_press_F', '4', 'Press Helmet');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Shades_Black', '4', 'Shades (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Shades_Blue', '4', 'Shades (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Shades_Green', '4', 'Shades (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Shades_Red', '4', 'Shades (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Spectacles', '4', 'Spectacle Glasses');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Spectacles_Tinted', '4', 'Tinted Spectacles');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Sport_Blackred', '4', 'Sport Shades (Vulcan)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Sport_Checkered', '4', 'Sport Shades (Style)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Sport_Blackyellow', '4', 'Sport Shades (Poison)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Sport_BlackWhite', '4', 'Sport Shades (Shadow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Sport_Greenblack', '4', 'Sport Shades (Yetti)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Sport_Red', '4', 'Sport Shades (Fire)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Squares', '4', 'Square Spectacles');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Aviator', '4', 'Aviator Glasses');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Lady_Blue', '4', 'Ladies Shades');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Tactical_Black', '4', 'Tactical Shades');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Tactical_Clear', '4', 'Tactical Glasses');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Lowprofile', '4', 'Low Profile Goggles');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Combat', '4', 'Combat Goggles');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_EyeProtectors_F', '4', 'Safety Goggles');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_EyeProtectors_Earpiece_F', '4', 'Safety Goggles (Earpiece)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_WirelessEarpiece_F', '4', 'Wireless Earpiece');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Respirator_yellow_F', '4', 'Respirator (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Plain_medical_F', '4', 'Identification Vest [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Safety_yellow_F', '4', 'Safety Vest (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Rangemaster_belt', '4', 'Rangemaster Belt');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_LegStrapBag_coyote_F', '4', 'Leg Strap Bag (Coyote)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_LegStrapBag_olive_F', '4', 'Leg Strap Bag (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_LegStrapBag_black_F', '4', 'Leg Strap Bag (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_DeckCrew_blue_F', '4', 'Deck Crew Vest (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_DeckCrew_brown_F', '4', 'Deck Crew Vest (Brown)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_DeckCrew_yellow_F', '4', 'Deck Crew Vest (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_DeckCrew_green_F', '4', 'Deck Crew Vest (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_DeckCrew_red_F', '4', 'Deck Crew Vest (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_DeckCrew_violet_F', '4', 'Deck Crew Vest (Violet)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_DeckCrew_white_F', '4', 'Deck Crew Vest (White)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Pocketed_coyote_F', '4', 'Multi-Pocket Vest (Coyote)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Pocketed_olive_F', '4', 'Multi-Pocket Vest (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Pocketed_black_F', '4', 'Multi-Pocket Vest (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_RebreatherB', '4', 'Rebreather [NATO]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Carryall_khk', '4', 'Carryall Backpack (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Bergen_tna_F', '4', 'Bergen Backpack (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Parachute', '4', 'Steerable Parachute');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('ItemWatch', '4', 'Watch');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('ItemMap', '4', 'Map');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('ItemGPS', '4', 'GPS');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('ItemCompass', '4', 'Compass');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('ToolKit', '4', 'Toolkit');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('Binocular', '4', 'Binoculars');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('Rangefinder', '4', 'Rangefinder');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Poor_1', '4', 'Worn Clothes');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Commoner1_1', '4', 'Commoner Clothes 2');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Poloshirt_blue', '4', 'Commoner Clothes (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Poloshirt_burgundy', '4', 'Commoner Clothes (Burgundy)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Poloshirt_redwhite', '4', 'Commoner Clothes (Red-White)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Poloshirt_salmon', '4', 'Commoner Clothes (Salmon)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Poloshirt_tricolour', '4', 'Commoner Clothes (Tricolor)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Man_casual_5_F', '4', 'Summer Clothes (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Man_casual_6_F', '4', 'Summer Clothes (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Man_casual_4_F', '4', 'Summer Clothes (Sky)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Man_casual_3_F', '4', 'Casual Clothes (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Man_casual_2_F', '4', 'Casual Clothes (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Man_casual_1_F', '4', 'Casual Clothes (Navy)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_man_sport_1_F', '4', 'Sport Clothes (Beach)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_man_sport_2_F', '4', 'Sport Clothes (Orange)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_man_sport_3_F', '4', 'Sport Clothes (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_IDAP_Man_cargo_F', '4', 'Aid Worker Clothes (Cargo) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_IDAP_Man_Jeans_F', '4', 'Aid Worker Clothes (Jeans) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_IDAP_Man_shorts_F', '4', 'Aid Worker Clothes (Polo, Shorts) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_IDAP_Man_Tee_F', '4', 'Aid Worker Clothes (Tee) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_IDAP_Man_TeeShorts_F', '4', 'Aid Worker Clothes (Tee, Shorts) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_IG_Guerilla2_2', '4', 'Guerilla Outfit (Pattern)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_OG_Guerilla2_3', '4', 'Guerilla Outfit (Plain, Light)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_IG_Guerilla2_1', '4', 'Guerilla Outfit (Plain, Dark)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_G_Story_Protagonist_F', '4', 'Worn Combat Fatigues (Kerry)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_IG_Guerilla3_2', '4', 'Guerilla Smocks 1');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_IG_Guerilla3_1', '4', 'Guerilla Smocks');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_HunterBody_grn', '4', 'Hunting Clothes');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_Competitor', '4', 'Competitor Suit');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Mechanic_01_F', '4', 'Mechanic Clothes');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_Journalist', '4', 'Journalist Clothes');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_Marshal', '4', 'Marshal Clothes');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_NikosBody', '4', 'Nikos Clothes');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_NikosAgedBody', '4', 'Underwear 1');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_OrestesBody', '4', 'Jacket and Shorts');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_WorkerCoveralls', '4', 'Worker Coveralls');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_ConstructionCoverall_Blue_F', '4', 'Construction Coverall (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_ConstructionCoverall_Red_F', '4', 'Construction Coverall (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_ConstructionCoverall_Black_F', '4', 'Construction Coverall (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_C_ConstructionCoverall_Vrana_F', '4', 'Construction Coverall (Vrana)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Press_F', '4', 'Vest (Press)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_TacVest_oli', '4', 'Tactical Vest (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_TacVest_khk', '4', 'Tactical Vest (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_TacVest_brn', '4', 'Tactical Vest (Brown)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_TacVest_blk', '4', 'Tactical Vest (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_TacVest_camo', '4', 'Tactical Vest (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_blk', '4', 'Assault Pack (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_cbr', '4', 'Assault Pack (Coyote)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_dgtl', '4', 'Assault Pack (Digital)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_khk', '4', 'Assault Pack (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_mcamo', '4', 'Assault Pack (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_ocamo', '4', 'Assault Pack (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_rgr', '4', 'Assault Pack (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_sgg', '4', 'Assault Pack (Sage)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_AssaultPack_Kerry', '4', 'US Assault Pack (Kerry)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_FieldPack_blk', '4', 'Field Pack (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_FieldPack_cbr', '4', 'Field Pack (Coyote)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_FieldPack_ocamo', '4', 'Field Pack (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_FieldPack_khk', '4', 'Field Pack (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_FieldPack_oli', '4', 'Field Pack (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_FieldPack_oucamo', '4', 'Field Pack (Urban)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_BergenC_grn', '4', 'Bergen (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_TacticalPack_oli', '4', 'Tactical Backpack (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_TacticalPack_mcamo', '4', 'Tactical Backpack (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_TacticalPack_blk', '4', 'Tactical Backpack (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_TacticalPack_ocamo', '4', 'Tactical Backpack (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_TacticalPack_rgr', '4', 'Tactical Backpack (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Kitbag_rgr', '4', 'Kitbag (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Kitbag_cbr', '4', 'Kitbag (Coyote)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Kitbag_mcamo', '4', 'Kitbag (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Kitbag_sgg', '4', 'Kitbag (Sage)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperLightHarness_ghex_F', '4', 'Viper Light Harness (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperLightHarness_khk_F', '4', 'Viper Light Harness (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperLightHarness_oli_F', '4', 'Viper Light Harness (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperLightHarness_blk_F', '4', 'Viper Light Harness (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperLightHarness_hex_F', '4', 'Viper Light Harness (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperHarness_ghex_F', '4', 'Viper Harness (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperHarness_khk_F', '4', 'Viper Harness (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperHarness_oli_F', '4', 'Viper Harness (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperHarness_blk_F', '4', 'Viper Harness (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_ViperHarness_hex_F', '4', 'Viper Harness (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Carryall_mcamo', '4', 'Carryall Backpack (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Carryall_ocamo', '4', 'Carryall Backpack (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Carryall_oli', '4', 'Carryall Backpack (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Carryall_oucamo', '4', 'Carryall Backpack (Urban)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Bergen_dgtl_F', '4', 'Bergen Backpack (Digital)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Bergen_hex_F', '4', 'Bergen Backpack (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_Bergen_mcamo_F', '4', 'Bergen Backpack (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_Rangemaster', '4', 'Rangemaster Suit');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_GEN_Commander_F', '4', 'Gendarmerie Commander Uniform');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_Wetsuit', '4', 'Wetsuit [NATO]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_survival_uniform', '4', 'Survival Fatigues');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_CombatUniform_mcam', '4', 'Combat Fatigues (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_CombatUniform_mcam_tshirt', '4', 'Combat Fatigues (MTP) (Tee)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_FullGhillie_lsh', '4', 'Full Ghillie (Lush) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_FullGhillie_sard', '4', 'Full Ghillie (Semi-Arid) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_FullGhillie_ard', '4', 'Full Ghillie (Arid) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_T_FullGhillie_tna_F', '4', 'Full Ghillie (Jungle) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_T_Sniper_F', '4', 'Ghillie Suit (Green Hex) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_T_Sniper_F', '4', 'Ghillie Suit (Tropic) [NATO]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_GhillieSuit', '4', 'Ghillie Suit [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_GhillieSuit', '4', 'Ghillie Suit [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_GhillieSuit', '4', 'Ghillie Suit [NATO]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Beret_blk_POLICE', '4', 'Beret (Police)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Beret_02', '4', 'Beret [NATO]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Beret_Colonel', '4', 'Beret [NATO] (Colonel)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_black', '4', 'Combat Helmet (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_camo', '4', 'Combat Helmet (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_desert', '4', 'Combat Helmet (Desert)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_grass', '4', 'Combat Helmet (Grass)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_tna_F', '4', 'Combat Helmet (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_light', '4', 'Light Combat Helmet');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_light_black', '4', 'Light Combat Helmet (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_light_desert', '4', 'Light Combat Helmet (Desert)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_light_grass', '4', 'Light Combat Helmet (Grass)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_light_sand', '4', 'Light Combat Helmet (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_light_snakeskin', '4', 'Light Combat Helmet (Snakeskin)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_Light_tna_F', '4', 'Light Combat Helmet (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_paint', '4', 'Combat Helmet (Spraypaint)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Helmet_Kerry', '4', 'Combat Helmet (Kerry)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_plain_blk', '4', 'Combat Helmet (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_plain_mcamo', '4', 'Combat Helmet (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_snakeskin', '4', 'Combat Helmet (Snakeskin)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_Enh_tna_F', '4', 'Enhanced Combat Helmet (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetCrew_B', '4', 'Crew Helmet [NATO]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetCrew_I', '4', 'Crew Helmet [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetCrew_O', '4', 'Crew Helmet [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetIA', '4', 'Modular Helmet');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetLeaderO_ocamo', '4', 'Defender Helmet (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetLeaderO_oucamo', '4', 'Defender Helmet (Urban)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetO_ocamo', '4', 'Protector Helmet (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetSpecB', '4', 'Enhanced Combat Helmet');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetSpecB_blk', '4', 'Enhanced Combat Helmet (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetSpecB_paint1', '4', 'Enhanced Combat Helmet (Grass)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetSpecB_paint2', '4', 'Enhanced Combat Helmet (Desert)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetSpecO_blk', '4', 'Assassin Helmet (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetSpecO_ocamo', '4', 'Assassin Helmet (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_PilotHelmetHeli_O', '4', 'Heli Pilot Helmet [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_PilotHelmetHeli_B', '4', 'Heli Pilot Helmet [NATO]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_PilotHelmetHeli_I', '4', 'Heli Pilot Helmet [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_CrewHelmetHeli_O', '4', 'Heli Crew Helmet [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_CrewHelmetHeli_I', '4', 'Heli Crew Helmet [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_PASGT_basic_blue_F', '4', 'Basic Helmet (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_TI_tna_F', '4', 'Stealth Combat Helmet');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Diving', '4', 'Diving Goggles');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_TacVest_blk_POLICE', '4', 'Tactical Vest (Police)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrier1_blk', '4', 'Carrier Lite (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrier2_blk', '4', 'Carrier Rig (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierSpec_blk', '4', 'Carrier Special Rig (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierGL_blk', '4', 'Carrier GL Rig (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('B_SCBA_01_F', '4', 'Self-Contained Breathing Apparatus');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_P07_snds_F', '4', 'P07 9 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_P07_khk_F', '4', 'P07 9 mm (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_9x21_Mag', '4', '9 mm 30Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('20Rnd_556x45_UW_mag', '4', '5.56 mm 20Rnd Dual Purpose Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_ACPC2_F', '4', 'ACP-C2 .45 ACP');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('9Rnd_45ACP_Mag', '4', '.45 ACP 9Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_Pistol_heavy_01_F', '4', '4-five .45 ACP');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('11Rnd_45ACP_Mag', '4', '.45 ACP 11Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_Pistol_heavy_02_F', '4', 'Zubr .45 ACP');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('6Rnd_45ACP_Cylinder', '4', '.45 ACP 6Rnd Cylinder');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_PDW2000_F', '4', 'PDW2000 9 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('SMG_02_F', '4', 'Sting 9 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('SMG_01_F', '4', 'Vermin SMG .45 ACP');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_45ACP_Mag_SMG_01', '4', '.45 ACP 30Rnd Vermin Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_556x45_Stanag', '4', '5.56 mm 30rnd Reload Tracer (Yellow) Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_01_blk_F', '4', 'SPAR-16 5.56 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_Katiba_C_F', '4', 'Katiba Carbine 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_Katiba_F', '4', 'Katiba 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_65x39_caseless_green', '4', '6.5 mm 30Rnd Caseless Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MXC_Black_F', '4', 'MXC 6.5 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MX_Black_F', '4', 'MX 6.5 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_65x39_caseless_mag', '4', '6.5 mm 30Rnd Sand Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_02_blk_F', '4', 'SPAR-16S 5.56 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('150Rnd_556x45_Drum_Mag_Tracer_F', '4', '5.56 mm 150Rnd Tracer (Red) Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('LMG_03_F', '4', 'LIM-85 5.56 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('200Rnd_556x45_Box_Tracer_Red_F', '4', '5.56 mm 200Rnd Tracer (Red) Box');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_07_blk_F', '4', 'CMR-76 6.5 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('20Rnd_650x39_Cased_Mag_F', '4', '6.5 mm 20Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_CTAR_blk_F', '4', 'CAR-95 5.8 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_580x42_Mag_F', '4', '5.8 mm 30Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MXM_Black_F', '4', 'MXM 6.5 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MX_SW_Black_F', '4', 'MX SW 6.5 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('100Rnd_65x39_caseless_black_mag_tracer', '4', '6.5 mm 100Rnd Tracer Black Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_06_camo_F', '4', 'Mk14 7.62 mm (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_06_olive_F', '4', 'Mk14 7.62 mm (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('20Rnd_762x51_Mag', '4', '7.62 mm 20Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_CTARS_blk_F', '4', 'CAR-95-1 5.8mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('100Rnd_580x42_Mag_Tracer_F', '4', '5.8 mm 100Rnd Tracer (Green) Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_ARX_blk_F', '4', 'Type 115 6.5 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('10Rnd_50BW_Mag_F', '4', '.50 BW 10Rnd Caseless Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MSBS65_mark_black_F', '4', 'Promet MR 6.5 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MSBS65_black_F', '4', 'Promet 6.5 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_65x39_caseless_msbs_mag', '4', '6.5 mm 30Rnd Promet Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('SMG_03_TR_black', '4', 'ADR-97 TR 5.7 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('SMG_03_black', '4', 'ADR-97 5.7 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_03_blk_F', '4', 'SPAR-17 7.62 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_EBR_F', '4', 'Mk18 ABR 7.62 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_03_F', '4', 'Mk-I EMR 7.62 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_AK12_F', '4', 'AK-12 7.62 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_762x39_Mag_F', '4', '7.62 mm 30Rnd AKM Reload Tracer (Yellow) Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_AK12U_F', '4', 'AKU-12 7.62 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('LMG_Mk200_F', '4', 'Mk200 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('200Rnd_65x39_cased_Box_Tracer', '4', '6.5 mm 200Rnd Belt Tracer (Yellow)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_02_F', '4', 'MAR-10 .338 (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_02_sniper_F', '4', 'MAR-10 .338 (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('10Rnd_338_Mag', '4', '.338 LM 10Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_RPK12_F', '4', 'RPK-12 7.62 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('75rnd_762x39_AK12_Mag_Tracer_F', '4', '7.62 mm 75rnd AK12 Tracer Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_04_tan_F', '4', 'ASP-1 Kir 12.7 mm (Tan)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('10Rnd_127x54_Mag', '4', '12.7 mm 10Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_05_blk_F', '4', 'Cyrus 9.3 mm (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('10Rnd_93x64_DMR_05_Mag', '4', '9.3 mm 10Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('LMG_Zafir_F', '4', 'Zafir 7.62 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('150Rnd_762x54_Box_Tracer', '4', '7.62 mm 150Rnd Tracer (Green) Box');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('MMG_02_black_F', '4', 'SPMG .338 (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('130Rnd_338_Mag', '4', '.338 NM 130Rnd Belt');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_LRR_F', '4', 'M320 LRR .408');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_LRR_camo_F', '4', 'M320 LRR .408 (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_LRR_tna_F', '4', 'M320 LRR .408 (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('7Rnd_408_Mag', '4', '.408 7Rnd LRR Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_GM6_F', '4', 'GM6 Lynx 12.7 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('5Rnd_127x108_Mag', '4', '12.7 mm 5Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('5Rnd_127x108_APDS_Mag', '4', '12.7 mm 5Rnd APDS Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_ACO_grn_smg', '4', 'ACO SMG (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_ACO_grn', '4', 'ACO (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Aco', '4', 'ACO (Red)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Holosight_smg', '4', 'Mk17 Holosight SMG');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Holosight', '4', 'Mk17 Holosight');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Holosight_smg_blk_F', '4', 'Mk17 Holosight SMG (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Holosight_blk_F', '4', 'Mk17 Holosight (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Holosight_khk_F', '4', 'Mk17 Holosight (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_MRCO', '4', 'MRCO');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_ERCO_blk_F', '4', 'ERCO (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Arco', '4', 'ARCO');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Hamr', '4', 'RCO');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_DMS', '4', 'DMS');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_DMS_ghex_F', '4', 'DMS (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('acc_pointer_IR', '4', 'IR Laser Pointer');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('acc_flashlight', '4', 'Flashlight');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('bipod_02_F_blk', '4', 'Bipod (Black) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('bipod_02_F_hex', '4', 'Bipod (Hex) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('bipod_02_F_tan', '4', 'Bipod (Tan) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('bipod_03_F_blk', '4', 'Bipod (Black) [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('bipod_03_F_oli', '4', 'Bipod (Olive) [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('bipod_01_F_khk', '4', 'Bipod (Khaki) [NATO]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_acp', '4', 'Sound Suppressor (.45 ACP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_65_TI_blk_F', '4', 'Stealth Sound Suppressor (6.5 mm, Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_H_MG', '4', 'Sound Suppressor LMG (6.5 mm)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_B', '4', 'Sound Suppressor (7.62 mm)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_m_snd_F', '4', 'Sound Suppressor (5.56 mm, Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_m_khk_F', '4', 'Sound Suppressor (5.56 mm, Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_58_blk_F', '4', 'Stealth Sound Suppressor (5.8 mm, Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_B_snd_F', '4', 'Sound Suppressor (7.62 mm, Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_B_khk_F', '4', 'Sound Suppressor (7.62 mm, Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_H_MG_khk_F', '4', 'Sound Suppressor LMG (6.5 mm, Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_H_MG_blk_F', '4', 'Sound Suppressor LMG (6.5 mm, Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Bandit_4_F', '4', 'Bandit Clothes (Checkered)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Bandit_5_F', '4', 'Bandit Clothes (Tank Top)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Bandit_1_F', '4', 'Bandit Clothes (Polo Shirt)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Bandit_3_F', '4', 'Bandit Clothes (Tee)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Bandit_2_F', '4', 'Bandit Clothes (Skull)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Para_2_F', '4', 'Paramilitary Garb (Jacket)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Para_4_F', '4', 'Paramilitary Garb (Tank Top)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Para_3_F', '4', 'Paramilitary Garb (Shirt)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Para_5_F', '4', 'Paramilitary Garb (Shorts)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_C_Soldier_Para_1_F', '4', 'Paramilitary Garb (Tee)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_IG_Guerilla1_1', '4', 'Guerilla Garment');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_IG_leader', '4', 'Guerilla Uniform');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_T_Soldier_F', '4', 'Combat Fatigues (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_T_Soldier_SL_F', '4', 'Recon Fatigues (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_OfficerUniform', '4', 'Combat Fatigues [AAF] (Officer)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_T_Officer_F', '4', 'Officer Fatigues (Green Hex) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_OfficerUniform_ocamo', '4', 'Officer Fatigues (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_CombatUniform_oucamo', '4', 'Fatigues (Urban) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_CombatUniform_ocamo', '4', 'Fatigues (Hex) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_T_Soldier_F', '4', 'Fatigues (Green Hex) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_HeliPilotCoveralls', '4', 'Heli Pilot Coveralls [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_pilotCoveralls', '4', 'Pilot Coveralls [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_O_PilotCoveralls', '4', 'Pilot Coveralls [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_CTRG_Soldier_F', '4', 'CTRG Stealth Uniform');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_B_CTRG_Soldier_2_F', '4', 'CTRG Stealth Uniform (Tee)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('U_I_Wetsuit', '4', 'Wetsuit [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Shemag_khk', '4', 'Shemag mask (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Shemag_olive', '4', 'Shemag (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Shemag_olive_hs', '4', 'Shemag (Olive, Headset)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_Shemag_tan', '4', 'Shemag mask (Tan)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_ShemagOpen_khk', '4', 'Shemag (White)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_ShemagOpen_tan', '4', 'Shemag (Tan)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_PASGT_basic_olive_F', '4', 'Basic Helmet (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetB_sand', '4', 'Combat Helmet (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetCrew_O_ghex_F', '4', 'Crew Helmet (Green Hex) [CSAT]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetO_oucamo', '4', 'Protector Helmet (Urban)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetO_ghex_F', '4', 'Protector Helmet (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('H_HelmetSpecO_ghex_F', '4', 'Assassin Helmet (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Bandanna_tan', '4', 'Bandana (Tan)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Bandanna_oli', '4', 'Bandana (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Bandanna_blk', '4', 'Bandana (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Bandanna_beast', '4', 'Bandana (Beast)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Bandanna_shades', '4', 'Bandana (Shades)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Bandanna_sport', '4', 'Bandana (Sport)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Bandanna_aviator', '4', 'Bandana (Aviator)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Balaclava_blk', '4', 'Balaclava (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Balaclava_oli', '4', 'Balaclava (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Balaclava_TI_tna_F', '4', 'Stealth Balaclava (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Balaclava_TI_blk_F', '4', 'Stealth Balaclava (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Balaclava_combat', '4', 'Balaclava (Combat Goggles)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('G_Balaclava_lowprofile', '4', 'Balaclava (Low Profile Goggles)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_BandollierB_blk', '4', 'Slash Bandolier (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_BandollierB_cbr', '4', 'Slash Bandolier (Coyote)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_BandollierB_khk', '4', 'Slash Bandolier (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_BandollierB_oli', '4', 'Slash Bandolier (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_BandollierB_rgr', '4', 'Slash Bandolier (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Chestrig_blk', '4', 'Chest Rig (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Chestrig_khk', '4', 'Chest Rig (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Chestrig_oli', '4', 'Chest Rig (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_Chestrig_rgr', '4', 'Chest Rig (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_HarnessO_brn', '4', 'LBV Harness');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_HarnessO_gry', '4', 'LBV Harness (Grey)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_HarnessOGL_brn', '4', 'LBV Grenadier Harness');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_HarnessOGL_gry', '4', 'LBV Grenadier Harness (Grey)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_I_G_resistanceLeader_F', '4', 'Tactical Vest (Stavrou)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_TacVestIR_blk', '4', 'Raven Vest');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrier1_rgr_noflag_F', '4', 'Carrier Lite (Green, No Flag)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrier1_tna_F', '4', 'Carrier Lite (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierL_CTRG', '4', 'CTRG Plate Carrier Rig Mk.1 (Light)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierIA1_dgtl', '4', 'GA Carrier Lite (Digital)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierIA2_dgtl', '4', 'GA Carrier Rig (Digital)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrier2_rgr', '4', 'Carrier Rig (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierH_CTRG', '4', 'CTRG Plate Carrier Rig Mk.2 (Heavy)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierSpec_mtp', '4', 'Carrier Special Rig (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierSpec_rgr', '4', 'Carrier Special Rig (Green)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierSpec_tna_F', '4', 'Carrier Special Rig (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_EOD_IDAP_blue_F', '4', 'EOD Vest (Blue) [IDAP]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_EOD_coyote_F', '4', 'EOD Vest (Coyote)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_EOD_olive_F', '4', 'EOD Vest (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierGL_mtp', '4', 'Carrier GL Rig (MTP)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierIAGL_oli', '4', 'GA Carrier GL Rig (Olive)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrierGL_tna_F', '4', 'Carrier GL Rig (Tropic)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_EOD_blue_F', '4', 'EOD Vest (Blue)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SDAR_F', '4', 'SDAR 5.56 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MK20_F', '4', 'Mk20 5.56 mm (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_Mk20_plain_F', '4', 'Mk20 5.56 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_AKS_F', '4', 'AKS-74U 5.45 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_545x39_Mag_F', '4', '5.45 mm 30Rnd Reload Tracer (Yellow) Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_TRG21_F', '4', 'TRG-21 5.56 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_01_khk_F', '4', 'SPAR-16 5.56 mm (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_01_snd_F', '4', 'SPAR-16 5.56 mm (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_02_snd_F', '4', 'SPAR-16S 5.56 mm (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_02_khk_F', '4', 'SPAR-16S 5.56 mm (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_CTAR_hex_F', '4', 'CAR-95 5.8 mm (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_CTAR_ghex_F', '4', 'CAR-95 5.8 mm (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MSBS65_camo_F', '4', 'Promet 6.5 mm (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MSBS65_sand_F', '4', 'Promet 6.5 mm (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MSBS65_F', '4', 'Promet 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MSBS65_mark_camo_F', '4', 'Promet MR 6.5 mm (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MSBS65_mark_sand_F', '4', 'Promet MR 6.5 mm (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MSBS65_mark_F', '4', 'Promet MR 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_AKM_F', '4', 'AKM 7.62 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MX_F', '4', 'MX 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MXC_F', '4', 'MXC 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MXC_khk_F', '4', 'MXC 6.5 mm (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MXM_F', '4', 'MXM 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MXM_khk_F', '4', 'MXM 6.5 mm (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_07_ghex_F', '4', 'CMR-76 6.5 mm (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_07_hex_F', '4', 'CMR-76 6.5 mm (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_ARX_ghex_F', '4', 'Type 115 6.5 mm (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_ARX_hex_F', '4', 'Type 115 6.5 mm (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MX_SW_F', '4', 'MX SW 6.5 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_MX_SW_khk_F', '4', 'MX SW 6.5 mm (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('100Rnd_65x39_caseless_mag_Tracer', '4', '6.5 mm 100Rnd Tracer Sand Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('100Rnd_65x39_caseless_khaki_mag_tracer', '4', '6.5 mm 100Rnd Tracer Khaki Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_01_F', '4', 'Rahim 7.62 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('10Rnd_762x54_Mag', '4', '7.62 mm 10Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_03_khaki_F', '4', 'Mk-I EMR 7.62 mm (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_03_tan_F', '4', 'Mk-I EMR 7.62 mm (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_03_woodland_F', '4', 'Mk-I EMR 7.62 mm (Woodland)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_03_multicam_F', '4', 'Mk-I EMR 7.62 mm (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_AK12U_arid_F', '4', 'AKU-12 7.62 mm (Arid)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_AK12U_lush_F', '4', 'AKU-12 7.62 mm (Lush)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_03_snd_F', '4', 'SPAR-17 7.62 mm (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_SPAR_03_khk_F', '4', 'SPAR-17 7.62 mm (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_05_tan_F', '4', 'Cyrus 9.3 mm (Tan)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_05_hex_F', '4', 'Cyrus 9.3 mm (Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_RPK12_lush_F', '4', 'RPK-12 7.62 mm (Lush)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('arifle_RPK12_arid_F', '4', 'RPK-12 7.62 mm (Arid)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('75Rnd_762x39_Mag_Tracer_F', '4', '7.62 mm 75Rnd AKM Tracer Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('75rnd_762x39_AK12_Lush_Mag_Tracer_F', '4', '7.62 mm 75rnd AK12 Tracer Lush Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('75rnd_762x39_AK12_Arid_Mag_Tracer_F', '4', '7.62 mm 75rnd AK12 Tracer Arid Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_DMR_02_camo_F', '4', 'MAR-10 .338 (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_GM6_camo_F', '4', 'GM6 Lynx 12.7 mm (Camo)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('srifle_GM6_ghex_F', '4', 'GM6 Lynx 12.7 mm (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_P07_F', '4', 'P07 9 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_Rook40_F', '4', 'Rook-40 9 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('hgun_Pistol_01_F', '4', 'PM 9 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('10Rnd_9x21_Mag', '4', '9 mm 10Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_MRD', '4', 'MRD');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Yorris', '4', 'Yorris J2');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('SMG_05_F', '4', 'Protector 9 mm');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('30Rnd_9x21_Mag_SMG_02', '4', '9 mm 30Rnd Mag');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_ERCO_snd_F', '4', 'ERCO (Sand)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_ERCO_khk_F', '4', 'ERCO (Khaki)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Arco_blk_F', '4', 'ARCO (Black)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('optic_Arco_ghex_F', '4', 'ARCO (Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_65_TI_ghex_F', '4', 'Stealth Sound Suppressor (6.5 mm, Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_65_TI_hex_F', '4', 'Stealth Sound Suppressor (6.5 mm, Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_58_wdm_F', '4', 'Stealth Sound Suppressor (5.8 mm, Green Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_58_hex_F', '4', 'Stealth Sound Suppressor (5.8 mm, Hex)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_PlateCarrier_Kerry', '4', 'US Plate Carrier Rig (Kerry)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_L', '4', 'Sound Suppressor (9 mm)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_H', '4', 'Sound Suppressor (6.5 mm)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('muzzle_snds_M', '4', 'Sound Suppressor (5.56 mm)');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('V_RebreatherIA', '4', 'Rebreather [AAF]');
INSERT INTO life_classnames(classname, type_id, slug) VALUES('75rnd_762x39_AK12_Lush_Mag_F', '4', '7.62 mm 75rnd AK12 Lush Mag');