COLOR_CORRECTION_REVIVE = ppEffectCreate["ColorCorrections", 500];
COLOR_CORRECTION_REVIVE ppEffectEnable true;
COLOR_CORRECTION_REVIVE ppEffectAdjust[1, 0.4, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0];
COLOR_CORRECTION_REVIVE ppEffectCommit 1;
DYN_BLUR_REVIVE = ppEffectCreate["DynamicBlur", 600];
DYN_BLUR_REVIVE ppEffectEnable true;
DYN_BLUR_REVIVE ppEffectAdjust[10];
DYN_BLUR_REVIVE ppEffectCommit 1;
player setUnconscious true;
life_wurdegedefit = true;
uiSleep(60 + random(20));
life_wurdegedefit = false;
player setUnconscious false;
player playMoveNow "AmovPercMstpSnonWnonDnon";
private _time = time + 60 + round (random 20);
waitUntil {_time - time <= 0 || life_isDead};
COLOR_CORRECTION_REVIVE ppEffectEnable false;
ppEffectDestroy COLOR_CORRECTION_REVIVE;
DYN_BLUR_REVIVE ppEffectEnable false;
ppEffectDestroy DYN_BLUR_REVIVE;